### ISSUE TITLE
Select a domain name

### ISSUE THREAD

**Issue by waldoj** [opendata/Gov-Data-Hosting#1]
Since the domain will appear in every hosted site, it's important to select something short, descriptive, and easy to ignore. That is, `springfield.usopendatahosting.net` would be horrible, but `springfield.govdata.net` would be just fine.

**Comment by waldoj** [comment]
It seems like any domain involving `gov` and `data` is good. I suppose `repo` is OK. The `org` and `net` TLDs are best for folks in government. `com` will do in a pinch. New-fangled TLDs are trouble.

**Comment by waldoj** [comment]
At some risk of squatters stumbling upon this, here are my top contenders:

govrepo.us
openrepo.org
opengovdata.net

**Comment by max-mapper** [comment]
what about `<name>.usopendata.org` ?

**Comment by waldoj** [comment]
Every hosted site is [name].[sitename].tld, so that would result in [name].[sitename].usopendata.org, which is a pretty egregious domain for governments to host their data at. :-/

**Comment by okdistribute** [comment]
avialable:
datapublished.org/com/net 
datalocations.org/com/net

Do you think that 'repo' is well known enough as a noun in these circles?

**Comment by waldoj** [comment]
> Do you think that 'repo' is well known enough as a noun in these circles?

Nope. But some guy in Texas is squatting on all the good domains. :-/

**Comment by okdistribute** [comment]
I like opengovdata.net although people often accidentally type in '.net'

Will people be mostly linking to this or saying it out loud?

**Comment by waldoj** [comment]
Yeah, I think I like the terminology in it the best, though I'm not thrilled with its length. I sure imagine that the domain will not often be spoken. And there's an extent to which a bit of awkwardness is OK, because we don't _want_ people to keep using this. We want them to go away and pay for proper hosting. :)

**Comment by waldoj** [comment]
I just bought `opengovdata.net`. Thanks for your help!
